# Generated by Django 3.1.1 on 2020-09-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='article_img/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='log',
            name='tags',
            field=models.ManyToManyField(blank=True, to='diary.Tag'),
        ),
    ]
