# Generated by Django 3.1.1 on 2020-09-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20200905_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='diary_img/%Y/%m/%d/'),
        ),
    ]
