# Generated by Django 3.1.1 on 2020-09-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200905_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='week',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=10),
        ),
    ]
