# Generated by Django 3.1.1 on 2020-09-05 10:47

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20200905_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='body',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
