# Generated by Django 3.1.1 on 2020-09-06 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20200905_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='week',
        ),
    ]
