# Generated by Django 3.1.1 on 2020-09-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_remove_log_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='excerpt',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
