# Generated by Django 3.1.1 on 2020-09-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_log_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
