# Generated by Django 3.1.1 on 2020-09-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
