# Generated by Django 3.1.1 on 2020-09-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_auto_20200910_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='log_tag', to='diary.Tag'),
        ),
    ]
