# Generated by Django 3.1.1 on 2020-09-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_auto_20200910_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='diary.Tag'),
        ),
    ]
