# Generated by Django 3.1.1 on 2021-01-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0018_auto_20210101_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='time',
        ),
    ]
