# Generated by Django 3.1.1 on 2021-01-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0019_remove_log_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='Article',
        ),
    ]
